j-sky-graceshopper/graceShopper

- client/store/index.js
- client/store/products.js
- server/api/index.js
- server/api/products.js
AllProducts for API server and redux
> AllProducts API and redux

- client/Routes.js
- client/components/AllProducts.js
- client/components/SingleProduct.js
Added dollar signs to All products and single product's page. Also, added "exact" to Route "/products"
> Changed products Routes and dollar signs added

- client/Routes.js
- client/components/AllProducts.js
- client/components/CategoryMenu.js
- client/components/Home.js
- client/components/Navbar.js
- client/components/SearchBar.js
- client/store/filter.js
- client/store/index.js
- client/store/products.js
- client/store/search.js
- package.json
- public/index.html
- public/style.css
- script/seed.js
- server/api/products.js
Added ability to filter by category
> filter by category in all products view

- client/Routes.js
- client/components/UpdateProduct.js
- client/store/products.js
- client/store/singleProduct.js
- server/api/products.js
Created Api, redux, and a component page to update products.
Created Route for UpdateProducts component.
> Route to update products

- client/Routes.js
- client/store/products.js
There was some duplicate code in the store/product.js file, I tried to resolve everything.
> fix merge conflict issues

- client/Routes.js
- client/components/AddProduct.js
- client/store/products.js
- server/api/index.js
- server/api/products.js
> Route for post product

- client/Routes.js
- client/store/auth.js
- script/seed.js
- server/auth/index.js
admin users weren't able to access add and edit forms
> fix authorization issues

- client/Routes.js
- client/components/AddProduct.js
- client/components/Cart.js
- client/components/Navbar.js
- client/components/SingleProduct.js
- client/components/UpdateProduct.js
- client/store/products.js
- public/style.css
created Cart component and displaying items in cart with total
> Cart component

- client/components/Cart.js
- client/store/cart.js
- client/store/categories.js
- client/store/index.js
- server/api/cart.js
- server/api/index.js
> fetch Cart from DB

- client/components/Cart.js
> fixed unAuthorized 401 error

- client/Routes.js
- client/components/AllProducts.js
- client/components/SingleProduct.js
Added Edit button to Single and all products' page.
Had to get rid of the "Div" in Routes so the Error route to "/edit/products/productId" doesn't happen. Cannot use div in Switch routes apparently.
> Added edit buttons to All Products and Single Products Page

- client/components/AllProducts.js
- client/store/products.js
- public/style.css
After editing an item an error occurred when trying to reroute to the all products page. This PR fixes that bug,.
> fix bug occurring when rerouting to all products after editing item

- client/components/Cart.js
- client/store/cart.js
- public/style.css
fixed bug where cart page would be empty when reloaded
> fix bug in reloading cart page

- public/style.css
change navbar to vertical when browser gets too narrow to show all items
> make nav bar responsive

- script/seed.js
add more products in seed file
> seed additional data

- client/components/AddToCart.js
- client/components/AllProducts.js
- client/components/AuthForm.js
- client/components/Cart.js
- client/components/CartIcon.js
- client/components/Home.js
- client/components/Navbar.js
- client/store/auth.js
- client/store/cart.js
- public/style.css
- server/api/cart.js
add cart button for logged in users, fix bug where cart item quantity wasn't showing until the page was refreshed, and style updates
> Add button

- client/components/AllProducts.js
- client/components/SingleProduct.js
- client/store/index.js
- client/store/products.js
- client/store/reviews.js
- client/store/singleProduct.js
- server/api/index.js
- server/api/products.js
- server/api/reviews.js
- server/db/index.js
Revised having reviews appear on Single Products page.
Added a delete button on reviews (on Single Product page) 
Added a delete button on a single product (on All products page)
** "onDelete: Cascade "  in Associations (server/db/index):
When a product is deleted, then the reviews are also deleted through association
> delete buttons on Reviews and a product

- client/components/SingleProduct.js
- server/api/products.js
include the user for each product review
> add user names to reviews

- client/components/AllProducts.js
- client/components/SearchBar.js
- server/api/cart.js
updated search feature to continuously update results as user types
> fix bug in search feature

- client/components/AddProduct.js
- client/components/UpdateProduct.js
- client/store/products.js
- server/api/gatekeepingMiddleware.js
- server/api/products.js
- server/db/models/User.js
I've set up a framework for adding in our express security middleware, took out of Post & Put routes for now (but will be super easy to add back in once working correctly!).  In the meantime I also helped make the sequelize requests more secure as well in the express routes.
> Express route security framework set up

- client/Routes.js
- client/components/AddUser.js
- client/components/AdminLanding.js
- client/components/AllUsers.js
- client/components/Navbar.js
- client/store/admin.js
- client/store/index.js
- public/style.css
- server/api/admin.js
- server/api/index.js
Admins can now see all users from route "/admin" (need to type in for now), not styled yet but functional!
> Admin access

- script/seed.js
- server/db/index.js
i seeded our reviews, categories, and products! i know it looks a mess, i will fix it up in the morning!! :)
> seeded reviews, categories, and products

- client/Routes.js
- client/components/AllUsers.js
- client/components/UpdateUser.js
- client/store/admin.js
- client/store/index.js
- client/store/singleUser.js
- server/api/admin.js
Created routes and component for editing a user and fetching a single user, in progress in the react component
> Edit User backend and front end set up

- client/Routes.js
- client/components/Cart.js
- client/components/Checkout.js
- client/components/Confirmation.js
- client/components/StripePaymentForm.js
- client/store/cart.js
- client/store/currentOrder.js
- public/style.css
- server/api/cart.js
- server/api/currentOrder.js
- server/db/models/User.js
> Checkout flow

- client/store/products.js
> Single product

- server/db/models/Product.spec.js
Added a Product model test spec on a new file under models
> Test specs

- client/store/cart.js
Updated the updateCart in store
> Fixed updateCart in store
